package com.ecommerce.saga.domain;

public enum SagaStep {
    ORDER_CREATED,
    PAYMENT_PROCESSING,
    INVENTORY_PROCESSING,
    SHIPPING_PROCESSING,
    ORDER_CONFIRMED,
    COMPENSATION_PAYMENT,
    COMPENSATION_INVENTORY,
    COMPENSATION_SHIPPING
}

